-- ============================================================
-- Oracle Donation Management System - Complete DDL
-- Database: XEPDB1
-- Schema: DONATION_APP
-- ============================================================

-- ============================================================
-- TABLE: Utilisateur (USERS)
-- ============================================================
CREATE TABLE Utilisateur (
    id_user        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_user      VARCHAR2(20) NOT NULL,
    nom_user       VARCHAR2(100) NOT NULL,
    email_user     VARCHAR2(100) NOT NULL UNIQUE,
    tel_user       VARCHAR2(20) NOT NULL,
    adresse_user   VARCHAR2(200),
    password_hash  VARCHAR2(200) NOT NULL,
    statut_user    VARCHAR2(20) DEFAULT 'ACTIVE',
    date_created   DATE DEFAULT SYSDATE
);

-- ============================================================
-- TABLE: Organisation
-- ============================================================
CREATE TABLE Organisation (
    id_org        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user_owner NUMBER NOT NULL,
    nom_org       VARCHAR2(100) NOT NULL,
    desc_org      VARCHAR2(500),
    tel_org       VARCHAR2(15),
    num_patente   VARCHAR2(100),
    lieu_org      VARCHAR2(200),
    statut_org    VARCHAR2(20) DEFAULT 'PENDING'
        CONSTRAINT chk_statut_org CHECK (statut_org IN ('PENDING', 'ACTIVE', 'SUSPENDED')),
    date_created  DATE DEFAULT SYSDATE,
    CONSTRAINT fk_org_owner FOREIGN KEY (id_user_owner)
        REFERENCES Utilisateur(id_user) ON DELETE CASCADE
);

-- ============================================================
-- TABLE: Action_social (Campaigns)
-- ============================================================
CREATE TABLE Action_social (
    id_action               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_org                  NUMBER NOT NULL,
    titre_action            VARCHAR2(100) NOT NULL,
    desc_action             VARCHAR2(1000),
    affiche_action          VARCHAR2(200),
    date_debut_action       DATE NOT NULL,
    date_fin_action         DATE NOT NULL,
    montant_objectif_action NUMBER(12,2),
    montant_recu_action     NUMBER(12,2) DEFAULT 0,
    statut_action           VARCHAR2(20) DEFAULT 'DRAFT'
        CONSTRAINT chk_action_statut CHECK (statut_action IN ('DRAFT', 'ACTIVE', 'CLOSED', 'COMPLETED')),
    date_created            DATE DEFAULT SYSDATE,
    CONSTRAINT fk_action_organisation FOREIGN KEY (id_org)
        REFERENCES Organisation (id_org) ON DELETE CASCADE,
    CONSTRAINT chk_action_dates CHECK (date_fin_action > date_debut_action)
);

-- ============================================================
-- TABLE: Besoin (Needs / Inventory Items)
-- ============================================================
CREATE TABLE Besoin (
    id_besoin          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_action          NUMBER NOT NULL,
    nom_besoin         VARCHAR2(100) NOT NULL,
    description_besoin VARCHAR2(500),
    type_besoin        VARCHAR2(100),
    unite_demande      NUMBER(10,0) NOT NULL
        CONSTRAINT chk_unite_demande CHECK (unite_demande > 0),
    unite_recue        NUMBER(10,0) DEFAULT 0
        CONSTRAINT chk_unite_recue CHECK (unite_recue >= 0),
    prix_unitaire      NUMBER(12,2),
    statut_besoin      VARCHAR2(20),
    pourcentage_rempli GENERATED ALWAYS AS
        (CASE
            WHEN unite_demande > 0 THEN ROUND((unite_recue / unite_demande) * 100, 2)
            ELSE 0
         END) VIRTUAL,
    date_created       DATE DEFAULT SYSDATE,
    CONSTRAINT fk_besoin_action FOREIGN KEY (id_action)
        REFERENCES Action_social (id_action) ON DELETE CASCADE
);

-- ============================================================
-- TABLE: Don (Donations)
-- ============================================================
CREATE TABLE Don (
    id_don       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_donateur  NUMBER NOT NULL,
    id_besoin    NUMBER NOT NULL,
    montant_don  NUMBER(12,2) NOT NULL
        CONSTRAINT chk_montant_don CHECK (montant_don > 0),
    date_don     DATE DEFAULT SYSDATE,
    statut_don   VARCHAR2(20) DEFAULT 'PENDING'
        CONSTRAINT chk_statut_don CHECK (statut_don IN ('PENDING', 'CONFIRMED', 'REJECTED')),
    preuve_don   VARCHAR2(200),
    date_created DATE DEFAULT SYSDATE,
    CONSTRAINT fk_don_donateur FOREIGN KEY (id_donateur)
        REFERENCES Utilisateur (id_user) ON DELETE CASCADE,
    CONSTRAINT fk_don_besoin FOREIGN KEY (id_besoin)
        REFERENCES Besoin (id_besoin) ON DELETE CASCADE
);

-- ============================================================
-- TABLE: Payment_Proofs (For BLOB storage of payment receipts)
-- ============================================================
CREATE TABLE Payment_Proofs (
    id_proof    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_don      NUMBER NOT NULL,
    file_name   VARCHAR2(255) NOT NULL,
    file_path   VARCHAR2(500),
    file_type   VARCHAR2(50),
    upload_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_proof_don FOREIGN KEY (id_don)
        REFERENCES Don (id_don) ON DELETE CASCADE
);


-- ============================================================
-- TABLE: Business_Log_Audit (Security & Audit)
-- ============================================================

CREATE TABLE Business_Log_Audit (
    id_audit        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      VARCHAR2(50)   NOT NULL,    
    record_pk       VARCHAR2(200),    
    operation       VARCHAR2(10)   NOT NULL
        CONSTRAINT chk_operation_2 CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),    -- 'INSERT','UPDATE','DELETE'
    old_values      VARCHAR2(2000),
    new_values      VARCHAR2(2000),
    changed_by      NUMBER,             -- USER or app user id later
    change_date     DATE DEFAULT SYSDATE
);

-- ============================================================
-- TABLE: Error_Log (Centralized error tracking)
-- ============================================================
CREATE TABLE Error_Log (
    id_error           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_code         VARCHAR2(50),
    error_message      VARCHAR2(500),
    source_procedure   VARCHAR2(100),
    error_date         DATE DEFAULT SYSDATE,
    details            CLOB
);

-- ============================================================
-- END OF DDL SCRIPT
-- ============================================================